### ISSUE TITLE
Simulation Enviroment setup

### ISSUE THREAD

**Issue by Crowdedlight** [DronesForBlood/DronesForBlood#10]
Setup Simulation Environment

**Comment by jlrandulfe** [comment]
A Gazebo simulation has been prepared and pushed to the develop branch.

The IRLock presents some problems when it's added to the simulation

**Comment by jlrandulfe** [comment]
A new launch file using a modification of the empty_world has been added. It spawns the iris drone with the IR lock, as well as the IR lock beacon on the floor
