### ISSUE TITLE
Data-link Loss Issue

### ISSUE THREAD

**Issue by Crowdedlight** [DronesForBlood/DronesForBlood#27]
Without mavlink_lora hardware to emulate heartbeat the data-link loss failsafe can't be enabled.

With mavlink_lora hardware we have a design question on how a data-link loss is recognized? As a perfect flight would have no messages from GCS to drone after takeoff, only reading msgs from drone to GCS

**Comment by jlrandulfe** [comment]
This issue should already be solved, as the GCS and the drone are both sending heartbeats to each other

**Comment by Crowdedlight** [comment]
Deprecated. When not using mavlink lora radio modules
