### ISSUE TITLE
The Gazebo simulation does not propagate some error messages through the mavlink

### ISSUE THREAD

**Issue by jlrandulfe** [DronesForBlood/DronesForBlood#29]
There are 2 error messages at least that are not sent through the ros topic, when an acknowledge is required. The messages are the following:

ERROR [mavlink] ERROR: wp index out of bounds
WARN  [navigator] First waypoint too far away: 47060 meters, 900 max.
ERROR [navigator] mission check failed

Ideally, the GCS master should be aware of this messages when it sends a command and asks back an acknowledge. However, it seems that anything is sent back through the acknowledge message.

**Comment by Crowdedlight** [comment]
Do the simulator console say that data-link is lost ? 
If the heartbeats isn't sent you won't get the status messages

**Comment by jlrandulfe** [comment]
The heartbeat is ok, and I am receiving other ack messages. But those errors are prompted in the Gazebo terminal and they are not propagated to the GCS master through mavlink. At least not in the response to the ack command (It answers ack is ok)

**Comment by Crowdedlight** [comment]
Those messages do not get output in any ack messages or as part of the ack messages from PX4. Those get sent though the statuslink topic. As this is PX4 logging with extra information. So you will get them by listen to "mavlnk_statustext" topic. This is how PX4 implemented it. We can't change that
