### ISSUE TITLE
Publish a heartbeat from all GCS nodes 

### ISSUE THREAD

**Issue by jlrandulfe** [DronesForBlood/DronesForBlood#32]

**Comment by Crowdedlight** [comment]
Heartbeat is given in format:
```c++
uint8 id //Id of the node. Chose one to give the node. The monitor uses id + name to recognize nodes
string name //name of node
float32 expected_interval //expected interval to receive heartbeats from the node. given in seconds float
string main_status //main status, like "Running, Error, Rebooting, Crashed and so on"
string current_task //current task the node is performing. To monitor what the nodes is doing
bool has_error //flag to set if node has detected error itself, but is still sending heartbeats. 
```
If Lora_ground_control is present on your system the message format can be from it. The msg is called: `heartbeat_node.msg` under the lora_ground_control package.

**Comment by Crowdedlight** [comment]
Topic: `/lora_ground_control/heartbeat_nodes_rx`

**Comment by Crowdedlight** [comment]
Implemented heartbeats on UTM node 035425cedccc40cb57b7ae56a2b4fe3b67e87a67

**Comment by jlrandulfe** [comment]
Added heartbeat from GCS master. Tested with lora monitor node

**Comment by jlrandulfe** [comment]
Added hearbeat from docking station. However, the TIMEOUT of lora should be lowered down, as it demands slow nodes to work much faster, and hence increase the GCS workload

**Comment by jlrandulfe** [comment]
I made a typo. The timeout should be raised

**Comment by Crowdedlight** [comment]
What timeout are we talking about here? Not sure what you mean. You set your own heartbeat period in your heartbeat?
