### ISSUE TITLE
Head towards a rally point if the battery is very low

### ISSUE THREAD

**Issue by jlrandulfe** [DronesForBlood/DronesForBlood#34]
The GCS master has to communicate to the pathplanner if there is an emergency situation. If that happens, the pathplanner has to create a path that ends in the rally point.

**Comment by jlrandulfe** [comment]
When an emergency situation, a decision has to be made:

- Go to the closest rally point

- Go to the docking station, as the drone is still able to get there

- land where it is now

**Comment by jlrandulfe** [comment]
@Crowdedlight shall we dismiss this issue? It'd be a good feature, but I think the drone firmware gives enough protection in case on an unexpected drop down of the battery level

**Comment by Crowdedlight** [comment]
For the theoretic/ideal system it should be handled, as the utm gives rally points. So you can navigate to a safe area while having battery to move around. 

But for our timeframe and monday, lets drop it. Just have to describe it in the report and how we would have done it. So it shows we have thought about it, but didn't manage to get it done

**Comment by F1nsk** [comment]
I have done a bare bones i intergration, where  doesnt peiorities where it should be heading

**Comment by jlrandulfe** [comment]
@F1nsk that was more focussed for #53, but it's true that we can addapt the code for that for this issue as well. I will think about it when I have some time tomorrow
