### ISSUE TITLE
Docking Station ROS Integration

### ISSUE THREAD

**Issue by Gilsaa** [DronesForBlood/DronesForBlood#35]
Create a ROS Node with topics etc. 
Everything should just be hardcoded, nothing actually has to work. 
Just has to show that we've thought about the integration.

**Comment by Crowdedlight** [comment]
Should be used for #44 too.

**Comment by Crowdedlight** [comment]
this can be done as hardcoded code in GCS master with a class too, if rosnode takes too long time

**Comment by Gilsaa** [comment]
Rosnode named "dock" has been created. 
Status from dock can be request by topic "/docklink/statusRequest" Type: Bool
Status will then be returned by topic "/doclink/statusPublish" Type: Bool
