### ISSUE TITLE
No flight zones on start and goal position

### ISSUE THREAD

**Issue by andkgl** [DronesForBlood/DronesForBlood#42]

**Comment by Crowdedlight** [comment]
I'd say:

in start zone:  stay on ground until it is cleared? Don't tell GCS Master that you are ready and that it should stay grounded. 

in goal: if already flying, find a rally point to land close by. (UTM gives rally points) 
in goal: if haven't taken off, stay grounded until a viable plan from start to finish is made with no zones. 

Maybe add possibility that if flying with payload, it can override and still land at goal, as it carries important medical supplies? I am not sure what makes sense here`?
