### ISSUE TITLE
Change ID of flight for UTM, based on when a payload is carried

### ISSUE THREAD

**Issue by Crowdedlight** [DronesForBlood/DronesForBlood#43]
The part that sends the drones current position and intentions to the UTM should change what ID is sent, based on if drone is carrying payload. 

id 3 = With payload, as we are now emergency/important

When no payload, should send id out as standard flying drone. So UTM and other drones know what drones to active avoid (id 3), and when other drones should avoid you. 

This also means we should be able to simulate that we add a payload, so the nodes know when we carry payload.

**Comment by jlrandulfe** [comment]
#44 Repeated issue
