### ISSUE TITLE
Get drone groundspeed and publish it, so it can be registered in the UTM

### ISSUE THREAD

**Issue by jlrandulfe** [DronesForBlood/DronesForBlood#46]

**Comment by Crowdedlight** [comment]
publish `GPS_RAW_INT` message, as it also give GPS fix that can be used in ground_control for stability in drawing drone path. Also gets "Course-over-ground", that isn't heading, but the current course over the ground. not sure if we can use that or even need it. 

https://mavlink.io/en/messages/common.html#GPS_RAW_INT

**Comment by Crowdedlight** [comment]
@jlrandulfe output will be on topic `mavlink_gps_raw`

Format will be this msg: 
```
uint64 time_usec //us
uint8 fix_type
float64 lat //dd
float64 lon //dd
float64 alt //m
uint16 eph
uint16 epv
float64 vel //m/s
float64 cog //deg
uint8 satellites_visible
```

Same format as in the common link. Groundspeed is given in cm/s in the "vel" parameter. 

If what he want is course over ground, which is given in `cdeg` you can get that directly from the `cog` parameter. (It is not heading, but direction of movement)

**Comment by Crowdedlight** [comment]
Do note that altitude is in **mm** if you ever plan on using it. And it is MSL altitude.

**Comment by Crowdedlight** [comment]
I changed some of the unit. This shows what units it gives correctly:
```cpp
uint64 time_usec //us
uint8 fix_type
float64 lat //dd
float64 lon //dd
float64 alt //m
uint16 eph
uint16 epv
float64 vel //m/s
float64 cog //deg
uint8 satellites_visible
```

**Comment by Crowdedlight** [comment]
Sent latest mavlink_lora with groundspeed. This issue should be solved @jlrandulfe
