### ISSUE TITLE
guide not working 

### ISSUE THREAD

**Issue by F1nsk** [DronesForBlood/DronesForBlood#47]
running `git submodule update --init --recursive `   returns this error 
`
error:  Server does not allow request for unadvertised object 0871a215fdca30aa779ab4d8996afd9507cec1ca
Fetched in submodule path 'simulation/Firmware', but it did not contain 0871a215fdca30aa779ab4d8996afd9507cec1ca. Direct fetching of that commit failed.
`
@jlrandulfe

**Comment by jlrandulfe** [comment]
The reference to the Firmware submodule was incorrect. It's fixed and working now in the develop branch
