### ISSUE TITLE
UX communication 

### ISSUE THREAD

**Issue by F1nsk** [DronesForBlood/DronesForBlood#50]
`[WARN] [1543667719.197863, 346.390000]: Could not process inbound connection: topic types do not match: [std_msgs/Bool] vs. [std_msgs/Int16MultiArray]{'message_definition': 'bool data', 'callerid': '/gcs_master', 'tcp_nodelay': '0', 'md5sum': '8b94c1b53db61fb6aed406028ad6332a', 'topic': '/dronelink/start', 'type': 'std_msgs/Bool'}
`

**Comment by Crowdedlight** [comment]
What topic is `dronelink/start` ? Not sure what node GCS_master is calling?

**Comment by jlrandulfe** [comment]
That is a typo. The name should be `userlink/start`. It was not changing for not altering the compatibility with the UserLink node, but it should definitely be changed.

**Comment by Gilsaa** [comment]
Topic prefix is changed to "userlink/" in newest commit of userlink.
Topic type of "userlink/start" was changed to Int16MultiArray, where element [1] contains either 0 or 1 if a package is onboard. GCS should be changed to accept this type.

**Comment by jlrandulfe** [comment]
Topic names in GCS master are changed now in the userlink branch. @Gilsaa, please test it with the userlink node, as I still have some troubles for running it in my laptop (I think I know why it doesn't run in my PC, I will fix it soon). Close the issue if it works

**Comment by F1nsk** [comment]
Seems to be working now.  Just needs the UAV's current location
