### ISSUE TITLE
Send and react on message when goal suddenly is in no flight zone

### ISSUE THREAD

**Issue by andkgl** [DronesForBlood/DronesForBlood#53]

**Comment by jlrandulfe** [comment]
As long as the path planner sends a new path, the GCS master should be prepared for dealing with this.

**Comment by andkgl** [comment]
Right now a message is send telling:

Epoch time when the zone is gone.
Distance to home
Location of home
Distance to the nearest rally point
Location of the nearest rally point

The GCS will have to decide what to do

**Comment by jlrandulfe** [comment]
Fixed
