### ISSUE TITLE
GCS Master - UTM - Status codes when Telemetry Lost

### ISSUE THREAD

**Issue by Crowdedlight** [DronesForBlood/DronesForBlood#60]
Send correct statuscodes depending on payload and emergency. 

When lost telemetry with drone, it should output "system failed" to utm so it knows the drone isn't working and other drones can avoid it. 

In case of lost telemetry the drone will land, as with no comms, we can't broadcast its position to UTM, so we would be a "ghost drone"

**Comment by jlrandulfe** [comment]
Added different possible situations to UTM status
