### ISSUE TITLE
Make Journal ready to input flights and data on monday

### ISSUE THREAD

**Issue by Crowdedlight** [DronesForBlood/DronesForBlood#64]
Acceptance flight needs a journal updated as specified. So every cycle flight can be well described how it went and what went wrong. Needs to be ready and gets filled in while testing.

```
During the AT, you must update a time based AT journal to be included as appendix to your project report.
The AT journal must contain entries for all test cycles stating pilot, GCS responsible, time, duration,
level of success, describe any problems and measures taken by the team to mitigate them etc.
```

**Comment by F1nsk** [comment]
Made a new folde called AT, where we can put any documents relating to the acceptance test.  Also made the journal, anyone is welcome to add points which make up a success full flight.
