### ISSUE TITLE
GCS FSM 

### ISSUE THREAD

**Issue by F1nsk** [DronesForBlood/DronesForBlood#75]
```
[INFO] [1544017032.845543, 227.582000]: FSM state: take_off
PATHPLANNER: Not ready! Current position is inside a no flight zone
PATHPLANNER: Unable to calculate a path. Missing information
PATHPLANNER: Unable to calculate a path. Missing information

```

should keep asking pp if it is ready

**Comment by jlrandulfe** [comment]
It's odd. It goes to TAKE_OFF state, which requires the path planner to be ready, but right after that it says it is not ready.

I'd need more info about the execution for debugging it. Maybe you can get the whole log of the execution

**Comment by jlrandulfe** [comment]
Before TAKE_OFF state, it actually asks continuosly the path planner to get ready.

**Comment by jlrandulfe** [comment]
Did not see the error again. Closing
