### ISSUE TITLE
UserInterface

### ISSUE THREAD

**Issue by Crowdedlight** [DronesForBlood/DronesForBlood#8]
**Features:**

- Communicate with the GCS

- Connect to a docking station. Show its status
    
  -  Free / Drone on-route / Docked drone / Out-of-service 

- Summon drone to current docking station (Only if status is "Free")

- Request drone to deliver to another docking station. If destination station is not "Free", the request will be sent to a "waiting" status

- Real-time status of all of the different docking stations

- Requested flight information
  
  - Estimated delivery time
  
  - Optimal path

- [ ] Design and select webapp system to make it in.
- [ ] Design backend
- [ ] Design Frontend

**Comment by jlrandulfe** [comment]
The client has specified that the UI should be a webapp, hence the previous work in Qt is deprecated.

**Comment by jlrandulfe** [comment]
Get GPS position from the mobile phone and use it in the interface
