### ISSUE TITLE
Add license, clean the project, and add a first version release

### ISSUE THREAD

**Issue by jlrandulfe** [DronesForBlood/DronesForBlood#91]
- [x] Add contact mail(s), and mention the dependency on mavlink lora

- [x] Removed all of the unused or temporary files and folders

- [x] Move UI files to a separate folder

- [x] Add docker files to a separate folder

- [x] Add License

- [ ] Launch release

**Comment by Crowdedlight** [comment]
@jlrandulfe just going with MIT license so all can use it?

**Comment by jlrandulfe** [comment]
that one is the most open one. I'm ok with it.

**Comment by Crowdedlight** [comment]
Added MIT license.

**Comment by Crowdedlight** [comment]
PR to master before merge is ongoing: #92
